-- 1차 답안.
SELECT K.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT B.INGREDIENT_TYPE, A.TOTAL_ORDER
FROM FIRST_HALF A
JOIN ICECREAM_INFO B
WHERE A.FLAVOR = B.FLAVOR) K
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC