SELECT B.ID, A.FISH_NAME, B.LENGTH
FROM FISH_NAME_INFO A
LEFT OUTER JOIN
    (SELECT t.ID, t.LENGTH, t.FISH_TYPE
    FROM FISH_INFO t
    JOIN
        (SELECT FISH_TYPE, MAX(LENGTH) as max_length
        FROM FISH_INFO
        GROUP BY FISH_TYPE) m
    ON t.FISH_TYPE = m.FISH_TYPE AND t.LENGTH = m.max_length) B
ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY ID ASC;